name: Pull Request
on:
  merge_group:

permissions:
  pull-requests: write

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: "Merge Build ${{ matrix.target }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: elmira
          - os: ubuntu-latest
            target: marlon
          - os: ubuntu-latest
            target: roland
          - os: ubuntu-latest
            target: vic

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v16
        with:
          name: tuckershea
          skipPush: true
          extraPullNames: nix-community

      - name: Build pr target
        env:
          TARGET: ".#top.${{ matrix.target }}"
        run: |
          set -o pipefail
          nix build $TARGET --show-trace --fallback -v --log-format raw > >(tee stdout.log) 2> >(tee /tmp/nix-pr-build.log >&2)

      - name: Output build failure
        if: failure()
        run: |
          drv=$(grep "For full logs, run" /tmp/nix-pr-build.log | grep -oE "/nix/store/.*.drv")
          nix log $drv
          echo $drv
          exit 1

      - name: Fetch current main and build it in a profile
        env:
          TARGET: "github:tuckershea/constellation#top.${{ matrix.target }}"
        run: nix build $TARGET -v --log-format raw --profile ./profile

      - name: Apply pr to profile
        env:
          TARGET: ".#top.${{ matrix.target }}"
        run: nix build $TARGET -v --log-format raw --profile ./profile

# Reference
# https://github.com/arianvp/nixos-stuff/blob/adec9e6/.github/workflows/pr.yml
# https://github.com/sandhose/nixconf/blob/055de30/.github/workflows/check-pr.yaml
# https://github.com/EdenEast/nyx/blob/7786a66554c5b8a888ca4b9b5c33129f06062eb7/.github/workflows/pr.yml
