name: Rotate Tailscale Keys

on:
  schedule:
    # Run at the start of each month
    # https://crontab.guru/#0_0_1_*_*
    - cron: '0 0 1 * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  rotate-tailscale-keys:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup cachix
        uses: cachix/cachix-action@v16
        with:
          name: tuckershea
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          # exclude nix-community so we build to our cache

      - name: Rotate Tailscale keys
        id: rotate-keys
        env:
          TS_API_CLIENT_ID: ${{ secrets.TS_API_CLIENT_ID }}
          TS_API_CLIENT_SECRET: ${{ secrets.TS_API_CLIENT_SECRET }}
        run: |
          # Run the key rotation script
          nix run .#rotate-tailscale-keys
          
          # Check if there are any changes
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.rotate-keys.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'chore: rotate Tailscale keys'
          branch: gha/rotate-tailscale-keys
          delete-branch: true
          title: 'Rotate Tailscale keys'
          body: |
            Automated Tailscale key rotation
            
            This PR was automatically generated by `.github/workflows/rotate-tailscale-keys.yml`.

